
---
apiVersion: v1
kind: PodTemplate
metadata:
  labels:
    workload.sas.com/class: stateless
  name: sas-qkb-bootstrap
template:
  metadata:
    annotations:
      sidecar.istio.io/inject: "false"
  spec:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: In
              values:
              - stateless
          weight: 100
        - preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: NotIn
              values:
              - cas
              - compute
              - connect
              - stateful
          weight: 50
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.azure.com/mode
              operator: NotIn
              values:
              - system
    containers:
    - args: null
      command: null
      image: sas-quality-knowledge-base
      imagePullPolicy: IfNotPresent
      name: sas-qkb-bootstrap
      volumeMounts:
      - mountPath: /rdutil
        name: sas-rdutil-dir
      - mountPath: /tgtdata
        name: sas-quality-knowledge-base-volume
    restartPolicy: Never
    tolerations:
    - effect: NoSchedule
      key: workload.sas.com/class
      operator: Equal
      value: stateful
    - effect: NoSchedule
      key: workload.sas.com/class
      operator: Equal
      value: stateless
    volumes:
    - name: sas-quality-knowledge-base-volume
      persistentVolumeClaim:
        claimName: sas-quality-knowledge-base
    - configMap:
        defaultMode: 493
        name: sas-reference-data-scripts
      name: sas-rdutil-dir
