# Migration Backup Patch Transformers
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-migration-mount
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/volumes/-
    value:
     name: cas-backup
     nfs:
       path: {{ NFS-MOUNT-PATH }}
       server: {{ NFS-SERVER }}
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/volumeMounts/-
    value:
      name: cas-backup
      mountPath: /casbackup
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1