# PatchTransformer to set and publish HTTP ports for CAS
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-publish-http
patch: |-
   - op: add
     path: /spec/publishHTTPService
     value: true
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1