apiVersion: v1
data:
  pgo-sub-command: pgo show cluster sas-crunchy-data-postgres
kind: ConfigMap
metadata:
  labels:
    sas.com/admin: cluster-local
    sas.com/deployment: sas-viya
  name: pgo-command
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/component-name: sas-crunchy-data-pgo-client
  labels:
    app.kubernetes.io/name: sas-scan-job
    sas.com/backup-job-type: "scan"
    workload.sas.com/class: stateless
  name: sas-crunchy-data-pgo-client
spec:
  template:
    metadata:
      annotations:
        sas.com/certificate-file-format: pem
      labels:
        workload.sas.com/class: stateless
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
      containers:
      - envFrom:
        - configMapRef:
            name: sas-shared-config
        env:
        - name: PGO_APISERVER_URL
          value: http://sas-crunchy-data-postgres-operator:8443
        - name: PGO_CA_CERT
          value: /tmp/tls.crt
        - name: PGO_CLIENT_CERT
          value: /tmp/tls.crt
        - name: PGO_CLIENT_KEY
          value: /tmp/tls.key
        - name: DISABLE_TLS
          value: "true"
        - name: PGO_SUBCOMMAND
          valueFrom:
            configMapKeyRef:
              name: pgo-command
              key: pgo-sub-command
        - name: PGO_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PGOUSERPASS
          valueFrom:
            secretKeyRef:
              key: password
              name: pgouser-pgoadmin
        - name: PGOUSERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: pgouser-pgoadmin
        image: sas-crunchy-data-pgo-client
        command: ["/bin/bash", "-c"]
        args: ["$(PGO_SUBCOMMAND) -n $(PGO_OPERATOR_NAMESPACE)"]
        name: sas-crunchy-data-pgo-client
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: temp
          mountPath: /temp
      volumes:
      - name: temp
        emptyDir: {}
      restartPolicy: Never
      serviceAccountName: pgo-pg
      imagePullSecrets: []
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless