
---
apiVersion: v1
data:
  sas-rdcopy.sh: |+
    #!/bin/sh
    umask 022
    SAS_RDNAME="`cat /payload/name`"
    echo "Attempting to deploy reference data '$SAS_RDNAME'..."
    SRCSHAFILE="/payload/check.sha1"
    SRCSHA=`cat "$SRCSHAFILE"`
    SRCDIR=/payload/content
    DSTDIR="/tgtdata/$SAS_RDNAME"
    DSTSHAFILE="/tgtdata/$SAS_RDNAME/$SAS_RDNAME.sha1"
    DSTSHA=
    [ -f "$DSTSHAFILE" ] && DSTSHA=`cat "$DSTSHAFILE"`
    COPYIT=1
    if [ -d "$DSTDIR" -a -n "$DSTSHA" ] ; then
        if [ "$SRCSHA" == "$DSTSHA" ] ; then
            echo "- Reference data with this same name and content already exists."
            echo "- No copy necessary."
        else
            echo "- Reference data with this same name, but different content, already exists."
            echo "- Skipping copy; existing content will not be overwritten."
        fi
        COPYIT=0
    fi
    if [ $COPYIT -eq 1 ] ; then
        echo "- Copying payload..."
        mkdir -p "$DSTDIR"
        cp -R "$SRCDIR"/* "$DSTDIR"
        cp "$SRCSHAFILE" "$DSTSHAFILE"
        chmod 644 "$DSTDIR"/*
        echo "- Done."
    fi

  sas-rdinit.sh: |+
    #!/bin/bash
    #/rdutil/sas-rdwait.sh || exit 1

  sas-rdlist.sh: |+
    #!/bin/sh
    ls /rdata | while read RD ; do
        INCTAG=
        [ -f "/rdata/$RD/$RD.sha1" ] || INCTAG=" (incomplete)"
        echo "$RD" "$INCTAG"
    done

  sas-rdremove.sh: |+
    #!/bin/sh

    RD_LABEL="$1"
    if [ ! -d "/rdata/$RD_LABEL" ] ; then
        echo "Reference data content \"$RD_LABEL\" was not found."
        exit 1
    fi
    rm -rf "/rdata/$RD_LABEL"
    echo "Reference data content \"$RD_LABEL\" was removed."

  sas-rdwait.sh: |+
    #!/bin/bash
    DATAPATH=/opt/sas/viya/home/share/refdata/qkb
    QKBCFGDIR=/qkb/config
    SAS_RDNAME="`cat $QKBCFGDIR/default`"
    if [ -z "$SAS_RDNAME" ] ; then
        echo "- No QKB configuration detected."
        exit 0
    fi
    SHAFILE="$DATAPATH/$SAS_RDNAME/$SAS_RDNAME.sha1"
    echo "Checking reference data: $SAS_RDNAME ..."
    while [ ! -f "$SHAFILE" ] ; do
        echo "- No SHA1 file at $SHAFILE; waiting..."
        sleep 10
    done
    echo "- Reference data $SAS_RDNAME is available."


kind: ConfigMap
metadata:
  annotations:
    orchestration.sas.com/literal: "true"
  name: sas-reference-data-scripts

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-data-quality-services
    sas.com/admin: namespace
  name: sas-data-quality
spec:
  ports:
  - name: dataquality
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: sas-data-quality-services
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-data-quality-services
    sas.com/admin: namespace
  name: sas-qkb-management
spec:
  ports:
  - name: qkbmanagement
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: sas-data-quality-services
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/kustomize-base: golang
    sas.com/pod-uses-db-migrator: "true"
    sas.com/pod-uses-readiness-probe: http
    sidecar.istio.io/proxyCPU: 15m
    sidecar.istio.io/proxyMemory: 115Mi
  labels:
    app.kubernetes.io/name: sas-data-quality-services
    sas.com/admin: namespace
    sas.com/deployment-base: golang
    workload.sas.com/class: stateless
  name: sas-data-quality-services
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-data-quality-services
  template:
    metadata:
      annotations:
        prometheus.io/path: /internal/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        sas.com/certificate-file-format: pem
        sas.com/kustomize-base: golang
        sas.com/pod-uses-readiness-probe: http
        sidecar.istio.io/proxyCPU: 15m
        sidecar.istio.io/proxyMemory: 115Mi
      labels:
        app: sas-data-quality-services
        app.kubernetes.io/name: sas-data-quality-services
        workload.sas.com/class: stateless
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
                - connect
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - sas-data-quality-services
              topologyKey: kubernetes.io/hostname
            weight: 100
      automountServiceAccountToken: true
      containers:
      - env:
        - name: SAS_K8S_DEPLOYMENT_NAME
          value: sas-data-quality-services
        envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - secretRef:
            name: sas-consul-client
        image: sas-data-quality-services
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          exec:
            command:
            - /opt/sas/viya/home/bin/sas-liveness-tool
            - -manifest-file
            - /opt/sas/viya/home/share/sas-data-quality-services/run-manifest.json
        name: sas-data-quality-services
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /internal/ready
            port: http
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /qkb
          name: sas-quality-knowledge-base-volume
      imagePullSecrets: []
      initContainers:
      - args:
        - cp -rf meta /data
        command:
        - /bin/sh
        - -c
        image: sas-data-quality-services
        imagePullPolicy: IfNotPresent
        name: hydrator
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 75m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: shared-vol
      - env:
        - name: SAS_SERVICE_NAME
          value: sas-data-quality-services
        envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - configMapRef:
            name: sas-java-config
        - secretRef:
            name: sas-consul-client
        image: sas-db-migrator
        imagePullPolicy: IfNotPresent
        name: sas-db-migrator
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 90Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: shared-vol
      securityContext:
        runAsNonRoot: true
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless
      volumes:
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: shared-vol
      - name: sas-quality-knowledge-base-volume
        persistentVolumeClaim:
          claimName: sas-quality-knowledge-base

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    sas.com/ha-class: centralized
    sas.com/kustomize-base: base
  name: sas-data-quality-services
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-data-quality-services

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    sas.com/ha-class: centralized
    sas.com/kustomize-base: golang
  name: sas-data-quality-services
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sas-data-quality-services

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-quality-knowledge-base
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
