# This block of code is for modifying the resource allocation for ephemeral
# storage. The default value is 8 gigabytes. The AMOUNT-OF-STORAGE should be a
# numeric value followed by the units, such as 16Gi for 16 gigabytes.
# In Kubernetes, the units for gigabytes is Gi.
# Modify ephemeral storage
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-modify-ephemeral-storage
patch: |-
   - op: replace
     path:/spec/controllerTemplate/spec/containers/0/resources/requests/ephemeral-storage
     value:
       {{ AMOUNT-OF-STORAGE}}
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1