apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/component-name: sas-backup-job
  labels:
    app.kubernetes.io/name: sas-scan-job
    sas.com/backup-job-type: "scan"
    workload.sas.com/class: stateless
  name: {{ JOB_NAME }}
spec:
  template:
    metadata:
      annotations:
        sas.com/certificate-file-format: pem
      labels:
        workload.sas.com/class: stateless
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
      containers:
      - envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - configMapRef:
            name: sas-java-config
        - configMapRef:
            name: sas-backup-job-parameters
        - secretRef:
            name: sas-consul-client
        env:
        - name: SAS_TLS_SKIP_VERIFY
          value: "true"
        - name: BACKUP_MOUNT_LOCATION
          value: /sasviyabackup
        - name: JOB_TYPE
          value: scan
        - name: USER
          value: {{ USER }}
        - name: COMPARE_INVENTORY_REPORTS
          value: "{{ COMPARE }}"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JOB_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['job-name']
        image: sas-backup-job
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: backup
          mountPath: /sasviyabackup
        name: sas-scan-job
      - env:
        - name: BACKUP_AGENT_TYPE
          value: REMOTE
        - name: SAS_TLS_SKIP_VERIFY
          value: "true"
        - name: BACKUP_MOUNT_LOCATION
          value: /sasviyabackup
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['job-name']
        envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - configMapRef:
            name: sas-java-config
        - configMapRef:
            name: sas-backup-agent-parameters
        - secretRef:
            name: sas-consul-client
        image: sas-backup-agent
        imagePullPolicy: IfNotPresent
        name: sas-backup-agent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: backup
          mountPath: /sasviyabackup
      volumes:
      - name: backup
        persistentVolumeClaim:
          claimName: sas-common-backup-data
      restartPolicy: Never
      serviceAccountName: sas-viya-backuprunner
      imagePullSecrets: []
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless