
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-e65dd6e9105d6516
patch: |-
  - op: add
    path: /spec/selector/matchExpressions
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-f741450077718f63
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/ports
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-eafd4f4c66b2e036
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/envFrom
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-41a715cccaad248a
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/env
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-96677086dfcaeb64
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0/volumeDevices
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-bb841c5e76f713f5
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/command
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-49771e67a6a5bbf3
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/args
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-bf336b2ed1e9987e
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/ports
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-b1631b9ca8612965
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/1/volumeDevices
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-3fa904aecfe4fb52
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/command
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-e758db707e621622
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/args
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-235cd23f5ea96e96
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/volumeDevices
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-058e93b1106161c5
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/readinessProbe/httpGet/httpHeaders
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-b28e1fb5a4d5eec9
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/supplementalGroups
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-72e01263d970d9b6
patch: |-
  - op: add
    path: /spec/template/spec/securityContext/sysctls
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-f082e0dffcc587b8
patch: |-
  - op: add
    path: /spec/template/spec/imagePullSecrets
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-5ad02b90cb175889
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-d70d5c4c1771abe4
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/preference/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-15ce795b658925e3
patch: |-
  - op: add
    path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/1/preference/matchFields
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-ff8ccaf46deffb2b
patch: |-
  - op: add
    path: /spec/template/spec/hostAliases
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-0b6263814f3c62c1
patch: |-
  - op: add
    path: /spec/template/spec/readinessGates
    value: []
target:
  group: apps
  kind: Deployment
  name: sas-score-definitions
  version: v1
