# General example for adding mounts to SAS containers with a
# PatchTransformer
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: data-mounts-deployment
patch: |-
  ## NFS path example - kubernetes will mount these for you
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: db-client-access
      mountPath: "/access-clients"
  - op: add
    path: /spec/template/spec/volumes/-
    value:
     name: db-client-access
     nfs:
       path: /export/access-clients
       server: XXX-nfs.okeworker.viya.oraclevcn.com
target:
  kind: Deployment
  annotationSelector: sas.com/sas-access-config=true
