
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-report-services-group
    sas.com/admin: namespace
  name: sas-report-alerts
spec:
  ports:
  - name: reportalerts
    port: 80
    protocol: TCP
    targetPort: reportalerts
  selector:
    app.kubernetes.io/name: sas-report-services-group
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-report-services-group
    sas.com/admin: namespace
  name: sas-report-images
spec:
  ports:
  - name: reportimages
    port: 80
    protocol: TCP
    targetPort: reportimages
  selector:
    app.kubernetes.io/name: sas-report-services-group
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-report-services-group
    sas.com/admin: namespace
  name: sas-report-templates
spec:
  ports:
  - name: reporttemplates
    port: 80
    protocol: TCP
    targetPort: reporttemplates
  selector:
    app.kubernetes.io/name: sas-report-services-group
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-report-services-group
    sas.com/admin: namespace
  name: sas-report-transforms
spec:
  ports:
  - name: reporttransform
    port: 80
    protocol: TCP
    targetPort: reporttransform
  selector:
    app.kubernetes.io/name: sas-report-services-group
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-report-services-group
    sas.com/admin: namespace
  name: sas-reports
spec:
  ports:
  - name: reports
    port: 80
    protocol: TCP
    targetPort: reports
  selector:
    app.kubernetes.io/name: sas-report-services-group
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sas.com/certificate-file-format: jks
    sas.com/kustomize-base: spring
    sas.com/pod-uses-readiness-probe: http
    sidecar.istio.io/proxyCPU: 15m
    sidecar.istio.io/proxyMemory: 115Mi
  labels:
    app.kubernetes.io/name: sas-report-services-group
    sas.com/admin: namespace
    sas.com/deployment-base: spring
    workload.sas.com/class: stateless
  name: sas-report-services-group
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-report-services-group
  template:
    metadata:
      annotations:
        prometheus.io/path: /internal/metrics
        prometheus.io/port: "10445"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        sas.com/certificate-file-format: jks
        sas.com/kustomize-base: spring
        sas.com/pod-uses-readiness-probe: http
        sidecar.istio.io/proxyCPU: 15m
        sidecar.istio.io/proxyMemory: 115Mi
      labels:
        app: sas-report-services-group
        app.kubernetes.io/name: sas-report-services-group
        workload.sas.com/class: stateless
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
      containers:
      - env:
        - name: SAS_K8S_DEPLOYMENT_NAME
          value: sas-report-services-group
        - name: JAVA_OPTION_SERVER_PORT
        - name: MANAGEMENT_SERVER_PORT
          value: ${sas.${spring.application.name}.management.server.port:10445}
        envFrom:
        - configMapRef:
            name: sas-java-config
        - configMapRef:
            name: sas-shared-config
        - secretRef:
            name: sas-consul-client
        - configMapRef:
            name: sas-spring-management-config
        image: sas-report-services-group
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: sas-report-services-group
        ports:
        - containerPort: 10445
          name: http-internal
          protocol: TCP
        - containerPort: 8080
          name: reports
          protocol: TCP
        - containerPort: 8081
          name: reportalerts
          protocol: TCP
        - containerPort: 8082
          name: reportimages
          protocol: TCP
        - containerPort: 8083
          name: reporttemplates
          protocol: TCP
        - containerPort: 8084
          name: reporttransform
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /internal/ready
            port: http-internal
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 50m
            memory: 1536M
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /opt/sas/viya/config/tmp
          name: tmp
      imagePullSecrets: []
      securityContext:
        runAsNonRoot: true
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless
      volumes:
      - emptyDir: {}
        name: tmp

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: sas-report-services-group
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sas-report-services-group
