
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-report-execution
    sas.com/admin: namespace
  name: sas-report-data
spec:
  ports:
  - name: reportdata
    port: 80
    protocol: TCP
    targetPort: reportdata
  - name: datacache1
    port: 35001
    protocol: TCP
    targetPort: datacache1
  - name: datacache2
    port: 35002
    protocol: TCP
    targetPort: datacache2
  - name: datacache3
    port: 35003
    protocol: TCP
    targetPort: datacache3
  selector:
    app.kubernetes.io/name: sas-report-execution
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-report-execution
    sas.com/admin: namespace
  name: sas-report-packages
spec:
  ports:
  - name: reportpackages
    port: 80
    protocol: TCP
    targetPort: reportpackages
  - name: pkgscache1
    port: 35004
    protocol: TCP
    targetPort: pkgscache1
  - name: pkgscache2
    port: 35005
    protocol: TCP
    targetPort: pkgscache2
  - name: pkgscache3
    port: 35006
    protocol: TCP
    targetPort: pkgscache3
  selector:
    app.kubernetes.io/name: sas-report-execution
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sas.com/certificate-file-format: jks
    sas.com/kustomize-base: spring
    sas.com/pod-uses-readiness-probe: http
    sidecar.istio.io/proxyCPU: 15m
    sidecar.istio.io/proxyMemory: 115Mi
  labels:
    app.kubernetes.io/name: sas-report-execution
    sas.com/admin: namespace
    sas.com/deployment-base: spring
    workload.sas.com/class: stateless
  name: sas-report-execution
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-report-execution
  template:
    metadata:
      annotations:
        prometheus.io/path: /internal/metrics
        prometheus.io/port: "10445"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        sas.com/certificate-file-format: jks
        sas.com/kustomize-base: spring
        sas.com/pod-uses-readiness-probe: http
        sidecar.istio.io/proxyCPU: 15m
        sidecar.istio.io/proxyMemory: 115Mi
      labels:
        app: sas-report-execution
        app.kubernetes.io/name: sas-report-execution
        workload.sas.com/class: stateless
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
      containers:
      - env:
        - name: SAS_K8S_DEPLOYMENT_NAME
          value: sas-report-execution
        - name: JAVA_OPTION_SERVER_PORT
        - name: MANAGEMENT_SERVER_PORT
          value: ${sas.${spring.application.name}.management.server.port:10445}
        - name: SAS_URL_reportData
          value: ${sas.url.service.scheme}://127.0.0.1:8080
        envFrom:
        - configMapRef:
            name: sas-java-config
        - configMapRef:
            name: sas-shared-config
        - secretRef:
            name: sas-consul-client
        - configMapRef:
            name: sas-spring-management-config
        image: sas-report-execution
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: sas-report-execution
        ports:
        - containerPort: 10445
          name: http-internal
          protocol: TCP
        - containerPort: 8080
          name: reportdata
          protocol: TCP
        - containerPort: 35001
          name: datacache1
        - containerPort: 35002
          name: datacache2
        - containerPort: 35003
          name: datacache3
        - containerPort: 8081
          name: reportpackages
          protocol: TCP
        - containerPort: 35004
          name: pkgscache1
        - containerPort: 35005
          name: pkgscache2
        - containerPort: 35006
          name: pkgscache3
        readinessProbe:
          httpGet:
            path: /internal/ready
            port: http-internal
        resources:
          limits:
            cpu: 2000m
            memory: 3Gi
          requests:
            cpu: 50m
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /opt/sas/viya/config/tmp
          name: tmp
      imagePullSecrets: []
      securityContext:
        runAsNonRoot: true
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless
      volumes:
      - emptyDir: {}
        name: tmp

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: sas-report-execution
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sas-report-execution
