apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-apply-security-context
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/securityContext
    value:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1